* description
  mac-install-utils is a script to setup basic Max OS X package management utils.
* prerequisite
  Many packages are installing from source. so you need to install xcode command line tools first to compile some source code.

  just type command below and fllow the instructions.
  
  #+BEGIN_SRC bash
  $gcc
  #+END_SRC

  and then click install button.

  verify your install by

  #+BEGIN_SRC bash
  $ xcode-select -p
  /Library/Developer/CommandLineTools
  #+END_SRC
  
* usage

   1. setup package manager

    #+BEGIN_SRC bash
     $\curl -sSL https://raw.github.com/ripple0328/mac-install-utils/master/basic-environment-installation.sh | bash
    #+END_SRC

   2. used as function
     
      after install basic environment installation, the script above will install
      the install-utils in your local machine. so you can use the bash function
      privode by install-utils seperately. for example you just want to install
      rvm.
     
      #+BEGIN_SRC bash
      $install-rvm
      #+END_SRC
     
      or 
     
      #+BEGIN_SRC bash
      $check-and-cask-install qq
      #+END_SRC
     
     
* what it setup
  * brew
  * brew-cask
  * git(hub)
* what it provide(as a bash function)
  * check-and-brew-install /package_name/
    check the existence of the brew package
    if not installed then install
  * check-and-npm-install  /package_name/
  * check-and-cask-install  /software_name/
  * check-and-gem-install  /gem_name/
  * check-and-install-brew-repo /repo_name/
  * check-comand-existence /command_name/
  * cleanup-command /command_name/
  * patch-shebang-path /file_name interpreter/
  * install-rvm
  * install-pow
  * install-tmate
  * cask-packages-path /software_name/
  * install-Inconsolata-powerline-font
* expample
  for an full example look at this project, installation script is in the bin
  directory:
  
  https://github.com/ripple0328/.emacs.d
